[package]
name = "find-process-or-window-title"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "psapi", "handleapi", "processthreadsapi", "tlhelp32", "winnt"] }
widestring = "0.5"
